services:
  ocrbox:
    image: ghcr.io/${GITHUB_REPOSITORY:-stefanahman/ocrbox}:latest
    container_name: ocrbox
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${OAUTH_SERVER_PORT:-8080}:8080"
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    pull_policy: always

