version: '3.8'

services:
  ocrbox:
    build: .
    container_name: ocrbox
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${OAUTH_SERVER_PORT:-8080}:8080"
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

